### PR TITLE
Code documentation and small refactoring

### PR DESCRIPTION
**Pull request by federicoB**
Removed some unused imports
Adjusted some code to PEP standard.
Added TODOs where the existing comment implicitly request modifications
In model test: if guardian is installed only if per-object permission are enabled. This fixes an error on system where guardian is installed but per object permission are disabled.
Removed useless documentation already present in annotator js documentation.
Removed user_has_perm method and replaced it with guardian user.has_perm
Replaced deprecated warn method of logger with warning
Removed useless override_settings decorator in AnnotationTestCase. Removing (if present) ObjectPermissionBackend has no effect.

### CODE REVIEW

**Comment by rlskoeser** [comment]
Hi @federicoB ! Thanks for your interest in this project and for your contributions, and I apologize for the delay in getting back to you.

What is the motivation for the PEP8 cleanup and all the changes to comments?  All of those changes are obscuring the more substantive contributions you're proposing, which makes it much harder to review and accept this pull request.

This codebase is adapted from an older project that didn't strictly adhere to PEP8, and I'm not sure how much effort it's worth to update everything to that standard.

Please revise this pull request (or create a new one, if that's easier) with _just_ the guardian clean up you're proposing.  I do like the improvement to the tests so that guardian is only installed when needed.

If you think the other clean up items are important, please propose them as individual pull requests so they can easily be reviewed and accepted in a more piecemeal fashion. We can certainly discuss here which pieces are important and worth that trouble before you go to the effort, and how we might group the changes.

**Comment by federicoB** [comment]
Hello Dr. @rlskoeser . 
I made the comments changes while reading the project to understand it. I felt those changes were necessary to improve the readability and to save time to ones who will want to contribute to project after me. There are some points in the code that weren't intuitive for me, so I spent time researching and understanding them and I don't want that someone else lose this time.
I understand though that natural language comments are subjective and so need a separate discussion.
Changes that improve readability for me can reduce it for you.
I created a single pull request thinking to save you time. But now I realize that I've made the opposite.
My apologies.
I am committed to split up this pull request and keep only the comments changes that are necessary.

I'm working on implementing public permission for anonymous users. I've already done that, with all test passing but I'm waiting to update the README and sphinx documentation. As soon I've made it I will commit on a separate branch so this pull request isn't messed up. I'm currently a bit busy with the uni, so I will work it on Sunday.

**Comment by rlskoeser** [comment]
@federicoB thanks.  I definitely want people to be able to read the code and understand it, but in some places I think your comments are less clear or even inaccurate.  If you still want to contribute those changes, please create a separate pull request so we can discuss the specifics and figure out how best to improve the code and the project for everyone.

**Comment by federicoB** [comment]
Closing this because I started to split this pull request in smaller ones.

**Pull request closed without merging**
